# Generated by Django 3.1.2 on 2020-12-10 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='tsync_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=55, primary_key=True, serialize=False, unique=True),
        ),
    ]
